spring.application.name=security-system
spring.datasource.url=jdbc:mysql://localhost:3306/codeguardian_db
spring.datasource.username=root
spring.datasource.password=Blessy21!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true